### ISSUE TITLE
PopOS bootable partition lost from boot manager after BIOS update

### ISSUE THREAD

**Issue by Brane-EAW** [system76/firmware-update#102]
I have a Thelio desktop whose BIOS was updated on 2024-02-17.  This is a dual boot system and the Windows partition remains bootable.  I'm using a single nvme drive for both PopOS and Windows.

I'd really like to recover my PopOS partition.  Any suggestions?

Thanks,
Ethan

**Comment by crubel** [comment]
I had a similar issue with my oryp7 when I updated the firmware and in my case I had to update the grub.efi file.  Seems older versions of grub do not work well with something to do with the changes made to the clock speed of one of the clocks.  I’m not sure exactly what the details are about this, but I was able to copy the newer version of this file to the efi boot location and then I could boot my other OS again successfully.  The proprietary bios have a setting for legacy non-efi/efi that apparently puts the affected clock(s) back to the old speed, but System76’ open bios has no such setting.
Might not be your issue but it took me weeks to find this information so I thought I would share it just in case…. Good luck..

**Comment by leviport** [comment]
Pop does not use grub, except on legacy BIOS systems, which oryp7 does not use. It uses systemd-boot instead.

This article might be helpful: https://support.system76.com/articles/bootloader

If you are still having trouble after that, I'd suggest opening a support ticket. Since you own System76 hardware, our support team will be happy to help you get back up and running.

**Comment by Brane-EAW** [comment]
@leviport, thanks for the article.  I'll let you know how it goes.

**Comment by Brane-EAW** [comment]
@leviport, I followed the instructions in the link you provided for fixing the bootloader and everything is working now.  Thanks for the help.
