### ISSUE TITLE
Boot order lost after firmware update succeeds

### ISSUE THREAD

**Issue by captainabernathy** [system76/firmware-update#106]
After performing the most recent update for 2023-09-08_42bf7a6 (oryp6), I was presented with the following message upon subsequent boots and reboots:

> SecureBoot is disabled.
> Booting from 'Samsung SSD 970 EVO Plus 1TB failed; verify it contains a 64-bit UEFI OS.
> Press any key to continue....

Then after pressing a key, the boot would succeed. 

Nonetheless, since no prior firmware updates produced this message, I was a bit alarmed. So I checked the boot order from the firmware menu and noticed that my boot order was no longer correct. Then after restoring the correct boot order, all subsequent boots have performed successfully and without interruption.

I'm bringing this up because I have not changed my boot order in several years and have never had any previous issues with any firmware updates affecting my boot order.

**Comment by crawfxrd** [comment]
Boot order was deleted because coreboot was updated from SMMSTOREv1 to SMMSTOREv2 in this update. This was a one-time occurrence to update the format for systems updating from <2021-12-21 to >2021-12-21.
