### ISSUE TITLE
Add link to full release notes to the UI

### ISSUE THREAD

**Issue by d4v3y0rk** [system76/firmware-update#18]
It would be nice to link to the full release notes in the UI of the firmware update utility. I am having a hard time even finding the full release notes for the update that just showed up on my system. 2020-8-13_f5d3306 is the name of the firmware package and there is a single line that describes the changes but it would be nice to see the full notes and the history of the firmware changes. I can't even find them.

**Comment by crawfxrd** [comment]
This is outside the scope of the project. firmware-update is only responsible for *applying* the updates. It is expected that users have already reviewed and accepted the changes via the OS application. Full release notes are in the `changelog.json` displayed by [pop-os/firmware-manager](https://github.com/pop-os/firmware-manager) (via [pop-os/system76-firmware](https://github.com/pop-os/system76-firmware)).
