### ISSUE TITLE
Protocol error flashing from firmware-open to proprietary

### ISSUE THREAD

**Issue by crawfxrd** [system76/firmware-update#25]
When flashing from System76 EC to ITE EC, I see:
```
Booting from item 0003
Set boot override to 0003
BIOS: Found
BIOS: Currently 2020-10-19_d5deed5
EC: Found
EC: Currently 2020-10-19_d5deed5
Press enter to comment flashing, the system may reboot...
SPI FILE: 16 MB
SPI ROM: 16 MB
SPI READ: 16 MB
  FLASH
    0: BIOS
    1: RW_MRC_CACHE
    2: SMMSTORE
    3: FMAP
    4: COREBOOT
SMMSTORE: found in old firmware, but not in new firmware
SPI WRITE: 16 MB
SPI VERIFY: 16 MB
BIOS: Success
Programming EC Backup ROM
ec board: Ok("system76/oryp6")
ec version: Ok("2020-10-19_d5deed5")
SPI Read 128K
SPI Write 128K
SPI Read 128K
Successfully programmed EC Backup ROM
EC Flash Error: Protocol(1)
EC tag: created Successfully
System will shut off in 5 seconds
```

On EC reset, ITE EC is used.

**Comment by Localacct21** [comment]
do you have the proprietary bioses for oryx pro 8?

**Comment by Sam948-byte** [comment]
I'm currently having this issue, addw3.  Here's the output when running`make flash_internal` `name@pop-os:~/firmware-open/ec$ make flash_internal
warning: unused manifest key: registries
warning: use of deprecated unit variant `hidapi::HidError::OpenHidDeviceError`
   --> src/main.rs:431:43
    |
431 |                     Err(hidapi::HidError::OpenHidDeviceError.into())
    |                                           ^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: `system76_ectool` (bin "system76_ectool") generated 1 warning
    Finished release [optimized] target(s) in 0.00s
[sudo] password for samf: 
file board: Ok("system76/addw3")
file version: Ok("2023-09-07_181d4c5-dirty")
ec board: Ok("system76/addw3")
ec version: Ok("2023-09-19_16ef69c")
Waiting 5 seconds for all keys to be released
Sync
Result: Err(Protocol(1))
Sync
System will shut off in 5 seconds
Sync
failed to flash 'build/system76/addw3/2023-09-07_181d4c5-dirty/ec.rom': Protocol(1)
make: *** [src/board/system76/common/common.mk:117: flash_internal] Error 1` any and all advice is appreciated
