### ISSUE TITLE
Current System76 Thelio R2 Firmware (F31b) Has AMD RdRand problem

### ISSUE THREAD

**Issue by asahaf** [system76/firmware-update#28]
Hi,

The current System76 Theiio R2 Motherboard firmware, which is based on Gigabyte F31b, has AMD CPU RdRand issue. The issue is fixed in Gigabyte update F31. 

Please refer to https://github.com/systemd/systemd/issues/18184 for more details.

System Info:
Machine: System76 Thelio R2
CPU: AMD Ryzen 9 5900X
Microcode update image (amd-ucode) version: 20201218.646f159-1
Motherboard: X570 i Aorus Pro Wifi
BIOS/Firmware Version: F31b (10/28/2020)
Arch Kernel Version: 5.10.5-arch1-1
Systemd Version: 247.2-1

**Comment by leviport** [comment]
Thank you for the report! We will prepare that firmware update, and it should be ready to release next week.

**Comment by asahaf** [comment]
Great, thanks. Please let me know when you publish the new firmware, as I'm currently using the Gigabyte firmware now instead of System76's

**Comment by asahaf** [comment]
@leviport F31 firmware has been replaced with F32 on Gigabyte website.

https://www.gigabyte.com/Motherboard/X570-I-AORUS-PRO-WIFI-rev-10/support#support-dl-bios

**Comment by leviport** [comment]
I see, thanks. It'll take a few days to start over from the progress I've made so far. Since F31 fixes the bug you reported, I'm going to proceed with it for now, then work on F32 as a lower priority.

**Comment by asahaf** [comment]
F31 has been completely removed from the list and replaced by F32. I wonder if there is a reason for that removal

**Comment by leviport** [comment]
Fair point, I'll leave that bug in the wild for another week then.

**Comment by leviport** [comment]
Item number 5 in their changelog does make it seem like something was acting flaky:

> 5. Improve system stability

Probably best to wait for F32.

**Comment by asahaf** [comment]
Yeah, you can make System76 firmware directly based on F32, skipping F31

**Comment by asahaf** [comment]
@leviport is it published already?

**Comment by leviport** [comment]
Not yet, but it should be going out early next week.

**Comment by asahaf** [comment]
Great! thank you

**Comment by leviport** [comment]
@asahaf F32 Z5 has been released and should be available soon through the firmware upgrade utility.

**Comment by asahaf** [comment]
Thanks
