### ISSUE TITLE
Will the tool work for converting Clevo NV40Mx to coreboot + EC?

### ISSUE THREAD

**Issue by tgroborsch** [system76/firmware-update#31]
Hi there,

I was wondering if this tool will eventually be useful to convert my Clevo NV40Mx Insyde-Bios machine to Coreboot + open EC? The mainboard is now recognized but as the proprietary model is named 'Not Applicable', the schedule --open call fails.

I read the instructions in your EC and firmware Repo where the flashing is described "the hard way" (Using SPI flasher / Mega 2560).
But at the same time it is said on your website (https://support.system76.com/articles/transition-firmware/) (Yes I saw this is available for a limited set of models)

> If you are running proprietary firmware and would like to transition to System76 Open Firmware, follow the steps above to install the updater from the command line, then run the following command to schedule the update:
> sudo system76-firmware-cli schedule --open

I'm curious to test your coreboot implementation once the Charging Threshold is stable.
With proprietary Firmware I'm facing some issues related to Thunderbolt docking and hope that some of it might be solved already (booting the machine with closed lid not possible; having to switch NUM lock each time; machine goes to standby on login if lid is closed).

Thanks and best regards

**Comment by jackpot51** [comment]
No
