### ISSUE TITLE
Problem with make all

### ISSUE THREAD

**Issue by chrom** [system76/firmware-update#53]
Run: make all

`
➜  firmware-update git:(master) make all

mkdir -p build/x86_64-unknown-uefi
cargo rustc \
	-Z build-std=core,alloc \
	-Z build-std-features=compiler-builtins-mem \
	--target x86_64-unknown-uefi \
	--release \
	-- \
	-C soft-float \
	--emit link=build/x86_64-unknown-uefi/boot.efi
error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
make: *** [Makefile:50: build/x86_64-unknown-uefi/boot.efi] Error 101
`

**Comment by crawfxrd** [comment]
You are not using the toolchain file; Your rustup is probably out of date.

```
rustup self update
```
